source "https://github.com/3721iot/RinoSmartPublicSpecs.git"
source "https://cdn.cocoapods.org/"

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

install! 'cocoapods', disable_input_output_paths: true, generate_multiple_pod_projects: true

use_frameworks! :linkage => :static

production = ENV["PRODUCTION"] == "1"

target 'RinoMatterExtension' do
  
  pod 'RinoMatterExtensionKit'
  
end

target 'Rino' do
  
  config = use_native_modules!

  # Flags change depending on  the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
#    :hermes_enabled => flags[:hermes_enabled],
    :hermes_enabled => false,
    :fabric_enabled => flags[:fabric_enabled],
#    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  pod 'RinoActivatorDefaultUISkin'
  pod 'RinoActivatorKit'
  pod 'RinoAppConfigModule'
  pod 'RinoAppUpgradeKit'
  pod 'RinoBaseKit'
  pod 'RinoBizCore'
  pod 'RinoBusinessLibraryModule'
  pod 'RinoCommonDefineKit'
  pod 'RinoDebugKit'
  pod 'RinoDeviceDetailDefaultUISkin'
  pod 'RinoDeviceKit'
  pod 'RinoFoundationKit'
  pod 'RinoHomeDefaultUISkin'
  pod 'RinoHomeKit'
  pod 'RinoIPCKit'
  pod 'RinoLanguageKit'
  pod 'RinoLaunchMenuKit'
  pod 'RinoLibraryModule'
  pod 'RinoMapBusinessLibrary'
  pod 'RinoMessageDefaultUISKin'
  pod 'RinoMessageKit'
  pod 'RinoMQTTKit'
  pod 'RinoNetworkRequestKit'
  pod 'RinoNFCDefaultUISKin'
  pod 'RinoNFCKit'
  pod 'RinoPanelKit'
  pod 'RinoProgressHUD'
  pod 'RinoScanBusinessKit'
  pod 'RinoScanKit'
  pod 'RinoSceneDefaultUISkin'
  pod 'RinoSceneKit'
  pod 'RinoThirdPartyVoiceKit'
  pod 'RinoUIKit'
  pod 'RinoUserDefaultUISkin'
  pod 'RinoUserSettingsDefaultUISkin'
  pod 'RinoWebViewKit'

  post_install do |installer|
    installer.generated_projects.each do |project|
      project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        end
      end
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '5.0'
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
    end
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
  pre_install do |installer|
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end

end
